(()=>{const d=document,h=d.documentElement,rm=matchMedia('(prefers-reduced-motion:reduce)').matches,go=()=>h.classList.add('go'),nl=()=>h.classList.add('nl');
const sc=d.querySelector('.hero-scene');if(sc)for(let i=0;i<13;i++){const s=d.createElement('span'),z=Math.random()<.25?2:1;s.className='st5';s.style.cssText=`left:${Math.random()*96+2}%;top:${Math.random()*52+2}%;width:${z}px;height:${z}px;--d:${3+Math.random()*4}s;--l:${Math.random()*5}s`;sc.prepend(s)}
if(rm||!h.classList.contains('i5')){go();nl();return}
const o=d.createElement('div');o.id='i5';o.innerHTML='<div class="i5s"><i class="i5p"></i><i class="i5p"></i><i class="i5p"></i></div>';d.body.append(o);
const st=o.firstChild,ps=[...st.children],E='cubic-bezier(.16,1,.3,1)',from=[[-120,80,-10],[0,-130,0],[120,80,10]],over=[[9,-6,1.5],[0,7,0],[-9,-6,-1.5]];d.body.style.overflow='hidden';
ps.forEach((p,i)=>{const[a,b,r]=from[i],[c,e,f]=over[i];p.animate([{opacity:0,transform:`translate(${a}px,${b}px) rotate(${r}deg) scale(.85)`},{opacity:1,offset:.25},{transform:`translate(${c}px,${e}px) rotate(${f}deg) scale(1.06)`,offset:.6},{transform:'none'}],{duration:2600,easing:E,fill:'both'});
const l=d.createElement('i');l.className='i5l';l.style.transform=`rotate(${Math.atan2(-b,-a)*57.3}deg)`;o.append(l);l.animate([{opacity:0,transform:`translate(${a*1.6}px,${b*1.6}px) rotate(${Math.atan2(-b,-a)*57.3}deg)`},{opacity:.9,offset:.4},{opacity:0,transform:`translate(0,0) rotate(${Math.atan2(-b,-a)*57.3}deg)`}],{duration:1500,easing:'ease-out',fill:'forwards'})});
setTimeout(()=>{for(let i=0;i<9;i++){const t=d.createElement('i');t.className='i5d';o.append(t);const an=i/9*6.28,r=50+Math.random()*40;t.animate([{opacity:.95,transform:'translate(0,0) scale(1)'},{opacity:0,transform:`translate(${Math.cos(an)*r}px,${Math.sin(an)*r}px) scale(.3) rotate(${i*40}deg)`}],{duration:900,easing:'ease-out',fill:'forwards'})}},1450);
const fin=()=>{const n=d.querySelector('.navbar .logo').getBoundingClientRect(),s=st.getBoundingClientRect(),k=n.width/s.width;st.style.transform=`translate(${n.left+n.width/2-innerWidth/2}px,${n.top+n.height/2-innerHeight/2}px) scale(${k})`;o.classList.add('out');setTimeout(go,500);setTimeout(()=>{nl();o.remove();d.body.style.overflow=''},1500)};
let done=0;const t=setTimeout(()=>{done=1;fin()},4300);o.onclick=()=>{if(!done){done=1;clearTimeout(t);fin()}};})();
